version: '3.1'

services:
  database:
    image: mysql:8.0.30
#    platform: linux/arm64v8
    container_name: isme-mysql
    ports:
      - "13307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: isme
      MYSQL_USER: isme
      MYSQL_PASSWORD: isme
    volumes:
      - ./docker/config/mysql:/docker-entrypoint-initdb.d
      - ./docker/data/mysql:/var/lib/mysql
    networks:
      isme-network:
        ipv4_address: 172.18.0.2
  redis:
    image: redis:7.0.5
#    platform: linux/arm64
    container_name: isme-redis
    ports:
      - "16379:6379"
    volumes:
      - ./docker/data/redis:/data
      - ./docker/config/redis:/etc/redis
    command: redis-server /etc/redis/redis.conf
    networks:
      isme-network:
        ipv4_address: 172.18.0.3

networks:
  isme-network:
    external: true
