spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: isme
    password: isme
    url: jdbc:mysql://127.0.0.1:13307/isme?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
